name = "github666"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

  "kv_namespaces": [
    {
      "binding": "KV",
      "id": "7f0211dda4a245ddb4ea45fdecf1af36",
      
    }
  ]
